config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Association
  belongs_to :user
  belongs_to :post

  # Validation
  validates :content, presence: true , length: { maximum: 300 }
end

app/models/like.rb
class Like < ApplicationRecord
  # Association
  belongs_to :user
  belongs_to :post

  # Validation
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  # full-text-search
  include PgSearch
  pg_search_scope :search_by_title, :against => :title, :using => { :tsearch => { :prefix => true } }

  # Scope
  default_scope { order(created_at: :desc) }

  # Image
  mount_uploader :image, ImageUploader

  # Association
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Validation
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Association
  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Validation
  validates_presence_of :user_name, :email, :password
  validates :user_name, length: { minimum: 4, maximum: 16 }
  validates :password, length: { minimum:8 }
  validates :email, uniqueness: true

  before_save :downcase_email

  def like? post_id
    likes.find_by_post_id(post_id)
  end

  private
    # Converts email to all lower-case
    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: :create

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.post = @post
    if @comment.save!
      respond_to do |format|
        format.js
      end
    else
      render root_path
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    if @comment
      @comment.destroy!
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end


  private

    def set_post
      @post = Post.find(params['post_id'])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :get_like, only: :create

  def create
    if @like
      @like.destroy!
    else
      @like = current_user.likes.create!(post_id: params['post_id'])
    end

    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_like
      @like = current_user.likes.find_by_post_id(params['post_id'])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = params['search'].present? ? Post.search_by_title(params['search']) : Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)
    respond_to do |format|
      if @post.save!
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy!
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :image)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div id="comment_<%= comment.id %>" class="comment">
  <div class="user-name">
    <%= comment.user.user_name %>
  </div>
  <div class="comment-content">
    <%= comment.content %>
  </div>
  <% if comment.user == current_user %>
    <%= link_to post_comment_path(comment.post, comment), method: :delete, remote: true, data: { confirm: "Are you sure?" } do %>
      <span class="glyphicon glyphicon-remove delete-comment"></span>
    <% end %>
  <% end %>
  <div class="time-ago">
    <%= time_ago_in_words comment.created_at %>
  </div>
</div>

app/views/comments/create.js.erb
$('#comments_<%= @comment.post_id %>').append("<%=j render 'comments/comment', post: @comment.post, comment: @comment %>");
$('#comment_content_<%= @comment.post_id %>').val('');

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstagramClone</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "Instagram", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "New Post", new_post_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li>  <%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <% flash.each do |type, msg| %>
      <% if type == "notice" %>
        <div class="alert alert-success">
      <% elsif type == "alert" %>
        <div class="alert alert-danger">
      <% else %>
        <div class='alert alert-<%= "#{type}" %>'>
      <% end %>
        <ul>
          <li>
            <%= msg %>
          </li>
        </ul>
      </div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/likes/_like.html.erb
<div class="like-button col-sm-12" id="likes_<%= post.id %>">
  <%= link_to '', post_likes_path(post), class: "glyphicon glyphicon-heart#{current_user.like?(post.id) ? '' : '-empty'}", remote: true, :method=>:post %>
  <span class="post-like-count"><%= post.likes.count %></span>
</div>

app/views/likes/create.js.erb
$('#likes_<%= @like.post_id %>').find('.post-like-count').html("<%= @like.post.likes.count %>");
<% if (current_user.like? @like.post_id) %>
  $('#likes_<%= @like.post_id %>').find('.glyphicon').removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
<% else %>
  $('#likes_<%= @like.post_id %>').find('.glyphicon').removeClass('glyphicon-heart').addClass('glyphicon-heart-empty');
<% end %>

app/views/posts/_form.html.erb
<% unless @post.image.url.nil? %>
  <div class="text-center">
    <%= image_tag @post.image.url(:medium) %>
  </div>
<% end %>

<div class="form-wrapper">
  <%= form_for(post) do |f| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group text-center">
      <%= f.label :image %>
      <%= f.file_field :image, class: 'form-control' %>
    </div>

    <div class="form-group text-center">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success form-control' %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= post.user.user_name %>
      </div>
      <div class="time-ago">
        <%= time_ago_in_words post.created_at %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
    </div>

    <div class="post-caption">
      <%= render 'likes/like', post: post %>
      <div class="caption">
        <div class="caption-content">
          <%= post.title %>
        </div>
      </div>
    </div>

    <div class="post-bottom">
      <div class="comments" id="comments_<%= post.id %>">
        <% if post.comments %>
          <%= render post.comments %>
        <% end %>
      </div>
    </div>

    <div class="comment-like-form row">
      <div class="comment-form col-sm-11">
        <%= form_for([post, post.comments.build], remote: true) do |f| %>
          <%= f.text_field :content, placeholder: 'Add a comment...', class: "form-control comment_content", id: "comment_content_#{post.id}" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

<div class="text-center edit-links">
  <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
  |
  <%= link_to "cancel", posts_path %>
</div>

app/views/posts/index.html.erb
<div class='posts-wrapper row'>
  <%= form_tag(posts_path, :method => 'get') do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search title...", class: "form-control", 'data-toggle' => 'tooltip', title: 'Enter to search' %>
  <% end %>
</div>

<div class="posts-wrapper row">
  <% @posts.each do |post| %>
    <%= render 'post', post: post %>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>
<% if @post.user.id == current_user.id %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
    |
    <%= link_to "Edit Post", edit_post_path(@post) %>
    |
    <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
<% else %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
  </div>
<% end %>